### ISSUE TITLE
Changing step value does not do anything

### ISSUE THREAD

**Issue by oxiumio** [ashvin27/react-time-range-slider#2]
Step appears to be 15 minutes despite of the value provided. Checked in /dist/index.js and it does not seem to have a function that would implement step change.
Please make changes or allow access to repo so I could create a PR for this.
Thank you

**Comment by DavidDronsfield** [comment]
Oxiumio is correct- the step prop does not work. Otherwise, this is a great little slider.

**Comment by ashvin27** [comment]
This issue is fixed in version: 1.1.2
